cover.small_garage_door:
  friendly_name: Small Garage Door
  icon: mdi:car
sensor.garage_car_present:
  entity_picture: /local/images/jagleaper.png
light.03640182cc50e3f87dc9:
  supported_features: 155
light.42728707cc50e3f8596d:
  supported_features: 155
light.03640182cc50e3f87fe8:
  supported_features: 155
binary_sensor.basement_door:
  device_class: door
binary_sensor.basement_motion:
  device_class: motion
binary_sensor.front_door:
  device_class: door
binary_sensor.mudroom_door:
  device_class: door
binary_sensor.deck_slider:
  device_class: door
binary_sensor.foyer_motion:
  device_class: motion
media_player.pandora:
  name: Pool Pandora
media_player.living_room:
  name: roku-livingroom
