garage:
  name: Garage
  entities:
    - cover.small_garage_door
    - sensor.garage_status
    - sensor.garage_car_present

alexa:
  name: Alexa
  entities:
    - media_player.jennifer_s_echo_dot
    - media_player.jennifer_s_echo_plus
#    - media_player.jennifer_s_echo_flex

garage_doors:
  name: Garage Doors
  entities:
    - sensor.garage_status

pool_pandora:
  name: Pool Pandora
  entities:
    - switch.04200099bcddc2003471
    - switch.pool_pandora

exterior_cameras_modetect:
  name: Exterior Cameras Modetect
  entities:
    - switch.frontyardcam_state
    - switch.frontdoorcam_state
    - switch.patiosouthcam_state
    - switch.pationorthcam_state

interior_cameras_modetect:
  name: Interior Cameras Modetect
  entities:
#    - switch.basementcam_state
    - switch.garagecam_state
    - switch.shopcam_state
    - switch.officecam_state

interior_lights:
  name: Interior Lights
  entities:
    - light.esplight_0259a5
    - light.esplight_5c7251
    - light.red_lamp
    - light.black_lamp

exterior_lights:
  name: Exterior Lights
  entities:
    - switch.shelly_shsw_25_b936ce_1
    - switch.shelly_shsw_25_b936ce_2
    - light.pationorthlight
    - light.patiosouthlight

christmas_lights:
  name: Christmas Lights
  entities:
    - switch.living_room_tree
    - switch.closet_wreath
    - switch.mini_tree
    - switch.black_cabinet
    - switch.pool_stereo_wp110b_main_channel
    - switch.tree_wp110b_main_channel
    - switch.christmas_zb_plug

office:
  name: Office
  entities:
    - switch.computer
    - switch.officecam_state_inversion

# Moved to light group in configuration.yaml
#patio_lights:
#  name: Patio Lights
#  entities:
#    - light.esplight_f8596d
#    - light.esplight_f87dc9
#hearth_room_lights:
#  name: Hearth Room Lights
#  entities:
#    - light.hearth_room_east_light
#    - light.hearth_room_west_light
