- id: '1607984767578'
  name: Morning Scene
  entities:
    group.christmas_lights:
      friendly_name: Christmas Lights
      state: 'on'
- id: Nighttime Scene
  name: Nighttime Scene
  entities:
    media_player.yamaha_receiver:
      friendly_name: Living Room Receiver
      state: 'off'
    media_player.yamaha_receiver_zone_2:
      friendly_name: Kitchen Stereo
      state: 'off'
    group.christmas_lights:
      friendly_name: Christmas Lights
      state: 'off'
    group.interior_lights:
      friendly_name: Indoor Lights
      state: 'off'
- id: '1608262635582'
  name: Movie Time
  entities:
    light.03640182cc50e3f87fe8:
      min_mireds: 153
      max_mireds: 370
      brightness: 50
      color_temp: 269
      friendly_name: Black Lamp
      supported_features: 155
      state: 'on'
    switch.living_room_tree:
      friendly_name: Tasmota-5233
      state: 'on'
    light.415110852cf4320259a5:
      min_mireds: 153
      max_mireds: 370
      friendly_name: LivingRoomEast
      supported_features: 3
      state: 'off'
    light.41511085dc4f225c7251:
      min_mireds: 153
      max_mireds: 370
      friendly_name: LivingRoomWest
      supported_features: 3
      state: 'off'
