- id: '1607984767578'
  name: Morning Scene
  entities:
    group.christmas_lights:
      friendly_name: Christmas Lights
      state: 'on'
- id: 'Nighttime Scene'
  name: Nighttime Scene
  entities:
    media_player.yamaha_receiver:
      friendly_name: Living Room Receiver
      state: 'off'
    media_player.yamaha_receiver_zone_2:
      friendly_name: Kitchen Stereo
      state: 'off'
    group.christmas_lights:
      friendly_name: Christmas Lights
      state: 'off'
