- id: '1607984767578'
  name: Morning Scene
  entities:
    group.christmas_lights:
      friendly_name: Christmas Lights
      state: 'on'
- id: Nighttime Scene
  name: Nighttime Scene
  entities:
    group.christmas_lights:
      friendly_name: Christmas Lights
      state: 'off'
- id: '1608262635582'
  name: Movie Time
  entities:
    switch.living_room_tree:
      friendly_name: Tasmota-5233
      state: 'on'
