alarmtogglechime:
  alias: Alarm Toggle Chime
  sequence:
  - data:
      entity_id: alarm_control_panel.home_alarm
      keypress: '*4'
    service: envisalink.alarm_keypress
goodnight_wrapper:
  alias: GoodNight Wrapper Script
  sequence:
  - data:
      entity_id:
      - switch.amzdestplug_left
    service: switch.turn_off
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.boolean_goodnight_script_error
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.boolean_alexa_goodnight
  - service: media_player.turn_off
    data:
      entity_id:
      - media_player.yamaha_receiver
      - media_player.yamaha_receiver_zone_2
  - service: script.turn_on
    data:
      entity_id:
      - script.enablemodetect
      - script.checkpoolgate
      - script.script_turn_off_lights_goodnight
      - script.script_christmas_lights_turn_off
  - delay: '2'
  - service: script.turn_on
    data:
      entity_id: script.checksheddoor
  - delay: '2'
  - service: script.turn_on
    data:
      entity_id: script.checkgaragedoors
  - delay: '2'
  - service: script.turn_on
    data:
      entity_id: script.goodnight_end
  mode: single
enablemodetect:
  alias: Enable MoDetect
  sequence:
  - data:
      entity_id:
      - switch.garagecam_state
      - switch.shopcam_state
      - switch.officecam_state
      - switch.pationorthcam_state
      - switch.patiosouthcam_state
      - switch.frontdoorcam_state
      - switch.drivewaycam_state
    service: switch.turn_on
  mode: single
checkgaragedoors:
  alias: Check Garage Doors
  sequence:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          state: 'on'
          entity_id: binary_sensor.garage_walk_in_door_contact
        - condition: state
          state: Open
          entity_id: sensor.small_garage_status
      sequence:
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: group.Alexa
          message: A garage door is open
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_goodnight_script_error
  mode: single
checkpoolgate:
  alias: Check Pool Gate Status
  sequence:
    choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.pool_gate_contact
        state: 'on'
      sequence:
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: group.Alexa
          message: The pool gate is open
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_goodnight_script_error
checksheddoor:
  alias: Check Shed Door Status
  sequence:
    choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.shed_door_contact
        state: 'on'
      sequence:
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: group.Alexa
          message: The shed door is open
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_goodnight_script_error
goodnight_end:
  alias: GoodNight End
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.boolean_goodnight_script_error
        state: 'on'
      sequence:
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: group.Alexa
          message: Are you sure you are ready for bed?
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_alexa_goodnight
    default:
    - service: automation.turn_on
      entity_id: automation.automation_to_turn_on_lights_in_the_morning
    - service: notify.alexa_media
      data:
        data:
          type: tts
        target: group.Alexa
        message: Goodnight
script_christmas_lights_turn_on:
  alias: Script Christmas Lights Turn On
  sequence:
  - service: homeassistant.turn_on
    data:
      entity_id: group.christmas_lights
  mode: single
script_christmas_lights_turn_off:
  alias: Script Christmas Lights Turn Off
  sequence:
  - service: homeassistant.turn_off
    data:
      entity_id: group.christmas_lights
  mode: single
script_turn_off_lights_goodnight:
  alias: Turn Off Lights at Alexa Goodnight
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.boolean_disable_bedside_lamps
        state: 'off'
      sequence:
      - service: light.turn_on
        data:
          entity_id: light.dads_lamp
          brightness: 25
      - service: light.turn_on
        data:
          entity_id: light.moms_lamp
          brightness: 35
  - service: light.turn_on
    data:
      entity_id: light.black_lamp
      brightness: 90
  - service: light.turn_on
    data:
      entity_id: light.hearth_room_lights
      brightness: 50
  - service: light.turn_off
    data:
      entity_id:
      - light.esplight_0259a5
      - light.esplight_5c7251
      - light.esplight_f87fe8
      - light.patio_lights
      - light.shelly_shsw_25_b936ce_1
      - light.shelly_shsw_25_b936ce_2
      - light.red_lamp
      - light.tasmota_5308
      - light.tasmota_3878
      - light.tasmota_4530
      - light.front_outside_garage_light
  - service: script.turn_on
    data:
      entity_id: script.mantellights32_goodnight
  - service: light.turn_on
    data:
      entity_id: light.upstairs_hallway_south
      brightness: 75
  - delay: '5'
  - service: light.turn_off
    data:
      entity_id: light.hearth_room_lights
      transition: 5
  - delay: '10'
  - service: light.turn_off
    data:
      entity_id: light.black_lamp
      transition: 5
  - delay: '15'
  - service: light.turn_off
    data:
      entity_id: light.upstairs_hallway_south
      transition: 3
  mode: single
desk_lights_white:
  alias: Desk Lights White
  sequence:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 169
      - 72
    entity_id: light.tasmota_5308
  mode: single
mantellights32_goodnight:
  alias: Mantellights32 Goodnight
  sequence:
  - service: mqtt.publish
    data:
      topic: cmnd/mantellights32/POWER
      payload: 'OFF'
      retain: true
  - service: mqtt.publish
    data:
      topic: cmnd/mantellights32/DeepSleepTime
      payload: 7200
      retain: true
  mode: single
mantellights32_goodmorning:
  alias: Mantellights32 Goodmorning
  sequence:
  - service: mqtt.publish
    data:
      topic: cmnd/mantellights32/DeepSleepTime
      payload: 900
      retain: true
  mode: single
sunrise_actions:
  alias: Sunrise Actions
  sequence:
  - service: fullykiosk.set_config
    data:
      entity_id: media_player.jennifer_s_5th_fire_media_player
      config_type: string
      key: screenBrightness
      value: '150'
  - service: fullykiosk.set_config
    data:
      entity_id: media_player.jennifer_s_5th_fire_media_player
      config_type: string
      key: screensaverBrightness
      value: '100'
  - service: fullykiosk.set_config
    data:
      entity_id: media_player.jennifer_s_5th_fire_media_player
      config_type: string
      key: timeToScreensaverV2
      value: '120'
  mode: single
