alarmtogglechime:
  alias: Alarm Toggle Chime
  sequence:
  - data:
      entity_id: alarm_control_panel.home_alarm
      keypress: '*4'
    service: envisalink.alarm_keypress
goodnight_wrapper:
  alias: GoodNight Wrapper Script
  sequence:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.boolean_goodnight_script_error
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.boolean_alexa_goodnight
  - scene: scene.nighttime_scene
  - service: script.turn_on
    data:
      entity_id:
      - script.enablemodetect
      - script.checkpoolgate
      - script.script_turn_off_lights
      - script.script_christmas_lights_turn_off
  - delay:
      seconds: 2
  - service: script.turn_on
    data:
      entity_id: script.checksheddoor
  - delay:
      seconds: 2
  - service: script.turn_on
    data:
      entity_id: script.checkgaragedoors
  - delay:
      seconds: 2
  - service: script.turn_on
    data:
      entity_id: script.goodnight_end
  mode: single
enablemodetect:
  alias: Enable MoDetect
  sequence:
  - data:
      entity_id:
      - switch.garagecam_state
      - switch.shopcam_state
      - switch.officecam_state
      - switch.pationorthcam_state
      - switch.patiosouthcam_state
      - switch.frontdoorcam_state
      - switch.drivewaycam_state
    service: switch.turn_on
  mode: single
checkgaragedoors:
  alias: Check Garage Doors
  sequence:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          state: 'on'
          entity_id: binary_sensor.garage_walk_in_door_contact
        - condition: state
          state: Open
          entity_id: sensor.small_garage_status
      sequence:
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: group.Alexa
          message: A garage door is open
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_goodnight_script_error
  mode: single
checkpoolgate:
  alias: Check Pool Gate Status
  sequence:
    choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.pool_gate_contact
        state: 'on'
      sequence:
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: group.Alexa
          message: The pool gate is open
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_goodnight_script_error
checksheddoor:
  alias: Check Shed Door Status
  sequence:
    choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.shed_door_contact
        state: 'on'
      sequence:
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: group.Alexa
          message: The shed door is open
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_goodnight_script_error
goodnight_end:
  alias: GoodNight End
  sequence:
    choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.boolean_goodnight_script_error
        state: 'on'
      sequence:
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: group.Alexa
          message: Are you sure you are ready for bed?
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_alexa_goodnight
    default:
    - service: automation.turn_on
      entity_id: automation.automation_to_turn_on_lights_in_the_morning
    - service: notify.alexa_media
      data:
        data:
          type: tts
        target: group.Alexa
        message: Goodnight
script_christmas_lights_turn_on:
  alias: Script Christmas Lights Turn On
  sequence:
  - service: homeassistant.turn_on
    data:
      entity_id: group.christmas_lights
  mode: single
script_christmas_lights_turn_off:
  alias: Script Christmas Lights Turn Off
  sequence:
  - service: homeassistant.turn_off
    data:
      entity_id: group.christmas_lights
  mode: single
script_turn_off_lights:
  alias: Turn Off Lights
  sequence:
  - service: light.turn_off
    data: {}
    entity_id: light.esplight_0259a5
  - service: light.turn_off
    data: {}
    entity_id: light.esplight_5c7251
  - service: light.turn_off
    data: {}
    entity_id: light.patio_lights
  - service: light.turn_off
    data: {}
    entity_id: light.shelly_shsw_25_b936ce_1
  - service: light.turn_off
    data: {}
    entity_id: light.shelly_shsw_25_b936ce_2
  - service: light.turn_on
    data:
      entity_id: light.dads_lamp
      brightness: 35
  - service: light.turn_on
    data:
      entity_id: light.moms_lamp
      brightness: 35
  - delay: '5'
  - service: light.turn_off
    data: {}
    entity_id: light.hearth_room_lights
  - service: light.turn_off
    data: {}
    entity_id: light.esplight_f87fe8
  mode: single
