version: '3.3'
services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        volumes:
            - '/etc/homeassistant/zigbee2mqtt/data:/app/data'
            - '/run/udev:/run/udev:ro'
        devices:
            - /dev/ttyACM0
        environment:
            - TZ=America/Chicago
        privileged: true
        network_mode: host
        image: koenkk/zigbee2mqtt
